#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
#

Name:       harbour-passviewer

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Pass Viewer
Version:    2.1
Release:    1
Group:      Applications/Productivity
License:    MIT/BSD
URL:        https://github.com/abranson/harbour-passviewer
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-passviewer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   qt5-qtdeclarative-import-positioning >= 5.2
Requires:   nemo-qml-plugin-notifications-qt5
Requires:   nemo-qml-plugin-dbus-qt5
Requires:   qt5-qtdeclarative-import-multimedia
Requires:   sailfishshare-components
Requires:   sailfish-components-pickers-qt5
Requires:   qt5-qtsvg-plugin-imageformat-svg
Requires(post): shared-mime-info
Requires(postun): shared-mime-info
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5Positioning)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(zxing) >= 3.0.2
BuildRequires:  pkgconfig(liblzma)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  bzip2-devel
BuildRequires:  desktop-file-utils

%description
Simple viewer for PassBook® files.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post
# >> post
update-mime-database %{_datadir}/mime > /dev/null 2>&1 || :
# << post

%postun
# >> postun
update-mime-database %{_datadir}/mime > /dev/null 2>&1 || :
# << postun

%files
%defattr(-,root,root,-)
%defattr(-,root,root,755)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/mime/packages/%{name}.xml
# >> files
# << files
